### ISSUE TITLE
Cannot set ambient by gocapability?

### ISSUE THREAD

**Issue by Mashimiao** [syndtr/gocapability#12]
Hello, I wrote a test program, as following:
package main

import (
    "fmt"
    "github.com/syndtr/gocapability/capability"
)

func main() {
    processCaps, err := capability.NewPid(0)
    if err != nil {
        fmt.Println("failed to create pid")
    }   
    processCaps.Set(capability.BOUNDING,capability.CAP_CHOWN)
    processCaps.Set(capability.EFFECTIVE,capability.CAP_CHOWN)
    processCaps.Set(capability.PERMITTED,capability.CAP_CHOWN)
    processCaps.Set(capability.INHERITABLE,capability.CAP_CHOWN)
    processCaps.Set(capability.AMBIENT,capability.CAP_CHOWN)
    if err := processCaps.Apply(capability.CAPS | capability.BOUNDS | capability.AMBIENT); err != nil {
        fmt.Println("failed to apply")
    }   

    processCaps2, err := capability.NewPid(0)
    if err != nil {
        fmt.Println("failed to create pid")
    }   
    set := processCaps2.Get(capability.AMBIENT, capability.CAP_CHOWN)
    if !set {
        fmt.Println("failed to set")
    }   
}

And the result is 
$ sudo go run test.go 
failed to set

Is there a bug with library or used it in a wrong way?

**Comment by Mashimiao** [comment]
ping @syndtr

**Comment by syndtr** [comment]
Sorry, I'm not that familiar with ambient capabilities. @justincormack any ideas?

**Comment by Mashimiao** [comment]
@syndtr  I just found the reason and fixed it in #13

**Comment by syndtr** [comment]
Merged. Thanks @Mashimiao
